Vagrant.configure("2") do |config|
  config.vm.box = "aspyatkin/ubuntu-18.04-server"
  
  config.vm.hostname = "docker-host"
  # config.vm.network "private_network", type: "dhcp"
  config.vm.network "private_network", ip: "172.28.128.22"
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
  
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = "docker-host-dev"
    v.linked_clone = true

    v.check_guest_additions = true
    if Vagrant.has_plugin?("vagrant-vbguest") then
      config.vbguest.auto_update = false
    end

    v.memory = 2048
    v.cpus = 1
  end

  config.vm.provision "shell", path: "./install_docker.sh"
  config.vm.provision "shell", path: "./install_packages.sh"
  
end
